name: Test code

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test codebase
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Run code tests
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn build
